const demoResources = [
  {id:1,title:'Financial Modeling for Entrepreneurs',type:'Course',provider:'Udemy',goal:'Build Business Acumen',skills:['Financial Modeling','Business Strategy'],status:'In Progress',progress:78,priority:'High',due:'Sep 27',hours:'15.6 / 20h',column:'in-progress',owner:'J',color:'blue',activity:[['Sep 20','Study · 1h'],['Sep 19','Practice · 45m'],['Sep 18','Watch · 1h 20m']]},
  {id:2,title:'AI Engineering Fundamentals',type:'Course',provider:'DeepLearning.AI',goal:'Become Better at AI',skills:['AI','Prompt Engineering'],status:'In Progress',progress:52,priority:'High',due:'Sep 30',hours:'8 / 16h',column:'in-progress',owner:'J',color:'blue',activity:[['Sep 20','Read · 40m'],['Sep 17','Study · 1h']]},
  {id:3,title:'Prompt Engineering',type:'Course',provider:'OpenAI Academy',goal:'Become Better at AI',skills:['AI','Prompt Engineering'],status:'Practice / Review',progress:64,priority:'Medium',due:'Oct 04',hours:'5.2 / 8h',column:'practice',owner:'R',color:'purple',activity:[['Sep 19','Practice · 50m']]},
  {id:4,title:'Digital Marketing Strategy',type:'Course',provider:'Reforge',goal:'Master Marketing',skills:['Marketing','Sales'],status:'Planned',progress:18,priority:'Medium',due:'Oct 12',hours:'2 / 14h',column:'planned',owner:'P',color:'orange',activity:[['Sep 12','Read · 2h']]},
  {id:5,title:'Leadership Fundamentals',type:'Book',provider:'Penguin',goal:'Improve Leadership',skills:['Leadership'],status:'Completed',progress:100,priority:'Low',due:'Sep 18',hours:'11 / 11h',column:'completed',owner:'J',color:'blue',activity:[['Sep 18','Read · 1h 30m'],['Sep 16','Read · 1h']]},
  {id:6,title:'Negotiation Masterclass',type:'Workshop',provider:'MasterClass',goal:'Build Business Acumen',skills:['Sales','Leadership'],status:'Backlog',progress:0,priority:'High',due:'Oct 20',hours:'0 / 6h',column:'backlog',owner:'R',color:'purple',activity:[]},
  {id:7,title:'Product Management Fundamentals',type:'Course',provider:'LinkedIn Learning',goal:'Build Business Acumen',skills:['Business Strategy'],status:'Completed',progress:100,priority:'Medium',due:'Sep 14',hours:'9 / 9h',column:'completed',owner:'J',color:'blue',activity:[['Sep 14','Completed · 1h']]},
  {id:8,title:'Advanced Excel',type:'Course',provider:'Coursera',goal:'Build Business Acumen',skills:['Financial Modeling'],status:'Planned',progress:12,priority:'Low',due:'Nov 02',hours:'1 / 10h',column:'planned',owner:'P',color:'orange',activity:[['Sep 10','Study · 1h']]}
];
const columns=[['backlog','BACKLOG'],['planned','PLANNED'],['in-progress','IN PROGRESS'],['practice','PRACTICE / REVIEW'],['completed','COMPLETED']];
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm.js';
export const supa = createClient(
  'https://zltqnsylerhcbnslqcqm.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsdHFuc3lsZXJoY2Juc2xxY3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4OTUyNDAsImV4cCI6MjEwNTQ3MTI0MH0.dmMVf1ZFdBsvHtD2vfZRcKSqyjqsSkAwqlDUB5aUzZk'
);
let resources=[]; let currentView='overview'; let searchTerm=''; let activeFilter='All';
let user = null;
const root=document.getElementById('view-container'); const modalBackdrop=document.getElementById('modal-backdrop'); const modal=document.getElementById('modal');
supa.auth.getUser().then(({data: {user}, error})=>{if(!error&&user){user=user;loadResources().then(render)}}).catch(console.error);
supa.auth.onAuthStateChanged((user)=>{this.user=user;loadResources().then(render)});
function save(){localStorage.setItem('learnflow-resources',JSON.stringify(resources)); saveToSupa()}
async function saveToSupa(){try{await supa.from('resources').upsert(resources)}catch(e){console.error('Supa save error',e)}}
async function loadResources(){const {data,error}=await supa.from('resources').select('*');if(!error&&data){resources=data.filter(r=>!user||r.owner===user.email?.split('@')[0]||r.owner===user.id||true)}else{resources=demoResources;save();}}
function resourceCard(r){return `<article class="course-card" data-id="${r.id}"><div class="card-top"><span class="type-label">${esc(r.type)} · ${esc(r.provider)}</span><span class="priority-dot ${r.priority.toLowerCase()}" title="${r.priority} priority"></span></div><h4>${esc(r.title)}</h4><div class="provider">${r.goal}</div><div class="card-progress"><div class="progress-caption"><span>Progress</span><b>${r.progress}%</b></div><div class="progress-track"><div class="progress-fill ${r.progress===100?'green':''}" style="width:${r.progress}%"></div></div></div><div class="tag-row">${r.skills.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div><div class="card-footer"><span class="due ${r.priority==='High'?'soon':''}">◷ ${r.due}</span><span class="avatar-stack"><span class="avatar avatar-${r.color}">${r.owner}</span></span></div></article>`}
function overview(){const userName=user?.email?.split('@')[0]||'Jeet';return `<div class="page"><div class="page-heading"><div><div class="eyebrow">Sunday, September 20, 2026</div><h1>Good morning ${userName}</h1><p>Make a little progress today. Your next step is already here.</p></div><div class="button-row"><button class="secondary-button" id="open-search">⌕ Search</button><button class="primary-button" id="add-learning">＋ Add learning</button><button class="icon-button" id="logout-btn" style="float:right;margin-left:10px">☾</button></div></div><div class="stats-grid"><div class="stat-card"><span class="stat-label">Courses</span><div class="stat-value">${resources.length}</div><span class="stat-meta">8 completed this year</span></div><div class="stat-card"><span class="stat-label">Overall progress</span><div class="stat-value">67%</div><span class="stat-meta positive">↑ 8% from last month</span></div><div class="stat-card"><span class="stat-label">Learning hours</span><div class="stat-value">29<span style="font-size:13px">h</span></div><span class="stat-meta">of 42h planned</span></div><div class="stat-card"><span class="stat-label">Active days</span><div class="stat-value">12</div><span class="stat-meta positive">↑ 3 this month</span></div></div><div class="overview-grid"><section class="panel sprint-panel"><div class="panel-header"><h3>Current sprint</h3><button class="panel-link" data-view-link="sprints">View sprint →</button></div><div class="sprint-content"><div class="sprint-title"><div class="sprint-icon">◷</div><div><strong>Sprint 04 · Build the foundation</strong><small>Sep 21 – Sep 27, 2026 · 5 days left</small></div></div><div class="progress-row"><span>Progress</span><b>78%</b></div><div class="progress-track"><div class="progress-fill" style="width:78%"></div></div><div class="sprint-footer"><div><strong>5</strong><span>courses planned</span></div><div><strong>3</strong><span>completed</span></div><div><strong>12h</strong><span>learning planned</span></div></div></div></section><section class="panel momentum-panel"><div class="panel-header"><h3>Learning momentum</h3><span class="status-pill done... (line truncated to 2000 chars)